---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workshop
  namespace: argocd
spec:
  description: Workshop Project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota and LimitRange
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  roles:
  # A role which provides read-only access to all applications in the project
  - name: read-only
    description: Read-only privileges to workshop
    policies:
    - p, proj:workshop:read-only, applications, get, workshop/*, allow
  - name: ci-role
    description: Sync privileges for workshop
    policies:
    - p, proj:workshop:ci-role, applications, sync, workshop/*, allow
...
