---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: workshop-argocd
spec:
  grafana:
    enabled: true
    route:
      enabled: true
  prometheus:
    enabled: true
    route:
      enabled: true
  server:
    route:
      enabled: true
...
